name: NotchApple
options:
  bundleIdPrefix: com.notchapple
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.8.0"
    CURRENT_PROJECT_VERSION: "11"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: YES
targets:
  NotchApple:
    type: application
    platform: macOS
    sources: [NotchApple, Shared]
    dependencies:
      - target: NotchWidget
        embed: true
    settings:
      base:
        PRODUCT_NAME: "Notch apple"
        PRODUCT_BUNDLE_IDENTIFIER: com.notchapple.app
        INFOPLIST_FILE: NotchApple/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: NotchApple/Resources/NotchApple.entitlements
        GENERATE_INFOPLIST_FILE: NO
  NotchWidget:
    type: app-extension
    platform: macOS
    sources: [NotchWidget, Shared]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notchapple.app.widget
        INFOPLIST_FILE: NotchWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: NotchWidget/NotchWidget.entitlements
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
