//
//  ClipboardHistory.swift
//  Notch apple
//
//  Clipboard manager: everything you copy is saved to a history you can
//  search, re-copy, pin and delete from the notch.
//
//  • Watches `NSPasteboard.general.changeCount` twice a second (the standard,
//    permission-free way; macOS has no clipboard-changed notification).
//  • Saves plain text, links, images and file references.
//  • Privacy: skips anything marked concealed or transient by the app that
//    copied it (password managers use `org.nspasteboard.ConcealedType`),
//    and never leaves this Mac. History is stored in Application Support.
//

import AppKit
import SwiftUI

struct ClipItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable { case text, link, image, files }

    var id = UUID()
    var kind: Kind
    var text: String?            // text / link
    var imageFile: String?       // PNG file name in the images folder
    var filePaths: [String]?     // copied files
    var sourceApp: String?
    var date = Date()
    var pinned = false

    var title: String {
        switch kind {
        case .text, .link: return text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        case .image: return "Image"
        case .files:
            let names = (filePaths ?? []).map { ($0 as NSString).lastPathComponent }
            return names.count == 1 ? names[0] : "\(names.count) files"
        }
    }

    var symbol: String {
        switch kind {
        case .text: "text.alignleft"
        case .link: "link"
        case .image: "photo"
        case .files: "doc.on.doc"
        }
    }
}

@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    @AppStorage("clipboard.limit") var limit = 200
    @AppStorage("clipboard.persist") var persist = true
    /// Pro: apps whose copies are never saved (bundle IDs, comma-separated).
    @AppStorage("clipboard.ignoredApps") var ignoredAppsRaw = ""

    var ignoredApps: [String] { ignoredAppsRaw.split(separator: ",").map(String.init) }
    /// Over 1,000 items needs Pro; without it the list keeps 1,000.
    var effectiveLimit: Int { limit > 1000 && !Entitlements.shared.canUse(.clipboardUnlimited) ? 1000 : limit }

    @Published private(set) var items: [ClipItem] = []

    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Set while we write to the pasteboard ourselves, so re-copying doesn't create a duplicate.
    private var ignoreNextChange = false

    private let folder: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("Notch apple/Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir.appendingPathComponent("images"), withIntermediateDirectories: true)
        return dir
    }()
    private var indexURL: URL { folder.appendingPathComponent("history.json") }
    private func imageURL(_ name: String) -> URL { folder.appendingPathComponent("images/\(name)") }

    /// Pasteboard types that mean "don't save me" (see nspasteboard.org).
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type", "com.apple.is-remote-clipboard",
    ]

    // MARK: Lifecycle

    func start() {
        guard timer == nil else { return }
        load()
        lastChangeCount = NSPasteboard.general.changeCount
        // Reading changeCount is cheap; tolerance lets macOS batch the wake-ups.
        timer = Power.timer(0.6) { [weak self] in self?.poll() }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: Capture

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        if ignoreNextChange { ignoreNextChange = false; return }

        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }   // passwords & secrets
        let front = NSWorkspace.shared.frontmostApplication
        if Entitlements.shared.canUse(.clipboardUnlimited), let id = front?.bundleIdentifier, ignoredApps.contains(id) { return }
        let source = front?.localizedName

        // Protect secrets (off by default): API keys, tokens, one-time codes and card numbers are kept out of the history and
        // cleared from the clipboard a little later, but only if nothing else has been copied since.
        if UserDefaults.standard.bool(forKey: "clipboard.protectSecrets"), let text = pb.string(forType: .string), SecretLogic.looksSecret(text) {
            let stamp = pb.changeCount
            let wait = Double(UserDefaults.standard.object(forKey: "clipboard.secretSeconds") as? Int ?? 30)
            DispatchQueue.main.asyncAfter(deadline: .now() + wait) { [weak self] in
                guard NSPasteboard.general.changeCount == stamp else { return }
                self?.ignoreNextChange = true
                NSPasteboard.general.clearContents()
                self?.lastChangeCount = NSPasteboard.general.changeCount
                self?.ignoreNextChange = false
            }
            return
        }

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            add(ClipItem(kind: .files, filePaths: urls.map(\.path), sourceApp: source))
        } else if let image = NSImage(pasteboard: pb), types.contains(NSPasteboard.PasteboardType.png.rawValue)
                    || types.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            guard let tiff = image.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff),
                  let png = rep.representation(using: .png, properties: [:]), png.count < 15_000_000 else { return }
            let name = UUID().uuidString + ".png"
            try? png.write(to: imageURL(name))
            add(ClipItem(kind: .image, imageFile: name, sourceApp: source))
        } else if let string = pb.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let isLink = URL(string: trimmed).map { $0.scheme == "http" || $0.scheme == "https" } ?? false
                && !trimmed.contains(" ")
            add(ClipItem(kind: isLink ? .link : .text, text: String(string.prefix(100_000)), sourceApp: source))
            ClipboardLink.shared.send(String(string.prefix(ClipboardLinkLogic.maxText)))   // only if you turned Clipboard Link on
        }
    }

    /// Text that arrived from another device: put it on this Mac's clipboard and in the history, without sending it back.
    func applyRemote(_ text: String, from device: String) {
        let pb = NSPasteboard.general
        ignoreNextChange = true
        pb.clearContents()
        pb.setString(text, forType: .string)
        lastChangeCount = pb.changeCount
        ignoreNextChange = false
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let isLink = URL(string: trimmed).map { $0.scheme == "http" || $0.scheme == "https" } ?? false && !trimmed.contains(" ")
        add(ClipItem(kind: isLink ? .link : .text, text: text, sourceApp: device))
    }

    private func add(_ item: ClipItem) {
        // Copying the same thing again moves it to the top instead of duplicating it.
        if let existing = items.firstIndex(where: { $0.kind == item.kind && $0.text == item.text
                                                    && $0.filePaths == item.filePaths && item.kind != .image }) {
            var moved = items.remove(at: existing)
            moved.date = .now
            items.insert(moved, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        save()
    }

    /// Keeps pinned items plus the newest unpinned ones up to the limit.
    private func trim() {
        var unpinned = 0
        items = items.filter { item in
            if item.pinned { return true }
            unpinned += 1
            if unpinned > effectiveLimit { removeFiles(of: item); return false }
            return true
        }
    }

    // MARK: Actions

    /// Puts an item back on the clipboard.
    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text, .link:
            pb.setString(item.text ?? "", forType: .string)
        case .image:
            if let name = item.imageFile, let image = NSImage(contentsOf: imageURL(name)) { pb.writeObjects([image]) }
        case .files:
            pb.writeObjects((item.filePaths ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        }
        ignoreNextChange = true
        if let i = items.firstIndex(of: item) {
            var moved = items.remove(at: i)
            moved.date = .now
            items.insert(moved, at: 0)
            save()
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].pinned.toggle()
        save()
    }

    func delete(_ item: ClipItem) {
        let before = items
        items.removeAll { $0.id == item.id }
        save()
        offerUndo("Clipboard item deleted", restoring: before, removed: [item])
    }

    /// Clears everything except pinned items.
    /// Panic hide: empties the system clipboard and (optionally) the unpinned history, with no undo toast.
    func panicWipe(history wipe: Bool) {
        ignoreNextChange = true
        NSPasteboard.general.clearContents()
        lastChangeCount = NSPasteboard.general.changeCount
        ignoreNextChange = false
        if wipe { items.removeAll { !$0.pinned }; save() }
    }

    func clearUnpinned() {
        let before = items
        let removed = items.filter { !$0.pinned }
        items.removeAll { !$0.pinned }
        save()
        offerUndo("Clipboard history cleared", restoring: before, removed: removed)
    }

    /// Images are only deleted from disk once the Undo has expired.
    private func offerUndo(_ message: String, restoring before: [ClipItem], removed: [ClipItem]) {
        UndoCenter.shared.offer(message) { [weak self] in self?.items = before; self?.save() }
        DispatchQueue.main.asyncAfter(deadline: .now() + 7) { [weak self] in
            guard let self else { return }
            for item in removed where !self.items.contains(where: { $0.id == item.id }) { self.removeFiles(of: item) }
        }
    }

    func image(for item: ClipItem) -> NSImage? {
        item.imageFile.flatMap { NSImage(contentsOf: imageURL($0)) }
    }

    // MARK: Persistence

    private func removeFiles(of item: ClipItem) {
        if let name = item.imageFile { try? FileManager.default.removeItem(at: imageURL(name)) }
    }

    private func save() {
        guard persist, let data = try? JSONEncoder().encode(items) else { return }
        try? data.write(to: indexURL, options: .atomic)
    }

    private func load() {
        guard persist, let data = try? Data(contentsOf: indexURL),
              let saved = try? JSONDecoder().decode([ClipItem].self, from: data) else { return }
        items = saved
    }

    /// Called when "Keep history after restart" is turned off.
    func forgetSavedHistory() {
        try? FileManager.default.removeItem(at: indexURL)
    }
}
