#!/usr/bin/env python3
"""Builds the emoji picker data for the Mac and Windows apps from Unicode's emoji-test.txt.
   curl -o /tmp/emoji-test.txt https://unicode.org/Public/emoji/latest/emoji-test.txt
   python3 scripts/gen_emoji.py /tmp/emoji-test.txt
Keeps emoji up to Unicode Emoji 14.0 (so they show on current macOS and Windows 11), drops skin-tone variants,
and adds a few everyday search words ("love" finds hearts). One line per entry: emoji|name|extra words."""
import re, sys

MAX_VERSION = 14.0
ALIASES = [  # name contains -> extra words (a leading = means the whole name)
    ("heart", "love"), ("grinning", "happy"), ("smiling", "happy smile"), ("joy", "lol laugh"), ("rolling on the floor", "lol rofl"),
    ("thumbs up", "ok yes like good approve"), ("thumbs down", "no bad dislike"), ("=fire", "hot lit"), ("party popper", "celebrate congrats tada"),
    ("clapping", "applause bravo"), ("folded hands", "pray thanks please"), ("check mark", "tick done yes correct"), ("cross mark", "no wrong x"),
    ("loudly crying", "sob"), ("crying", "sad tear"), ("pile of poo", "poop"), ("=rocket", "launch ship"), ("=eyes", "look see"), ("=sparkles", "magic new shiny"),
    ("red heart", "love"), ("face with tears of joy", "lol laugh"), ("=skull", "dead"), ("waving hand", "hello hi bye"), ("light bulb", "idea"),
    ("=warning", "caution"), ("money", "cash"), ("birthday cake", "bday"), ("=thinking", "hmm"), ("winking", "flirt"), ("sleeping", "tired zzz"),
    ("angry", "mad"), ("pouting", "mad"), ("=sun", "sunny"), ("rainbow", "pride"), ("hundred points", "100 perfect"), ("=bug", "insect"),
]
SYMBOLS = """→|right arrow|
←|left arrow|
↑|up arrow|
↓|down arrow|
↔|left right arrow|
⇒|implies double arrow|
⇐|left double arrow|
✓|check mark tick|
✗|ballot x cross|
≈|approximately equal|
≠|not equal|
≤|less than or equal|
≥|greater than or equal|
±|plus minus|
×|multiplication times|
÷|division|
∞|infinity|
√|square root|
π|pi|
°|degree|
©|copyright|
®|registered|
™|trade mark|
€|euro|
£|pound sterling|
¥|yen yuan|
₹|rupee|
¢|cent|
•|bullet|
…|ellipsis|
–|en dash|
—|em dash|
«|left guillemet quote|
»|right guillemet quote|
§|section|
¶|paragraph pilcrow|
†|dagger|
¿|inverted question mark|
¡|inverted exclamation mark|
½|one half|
¼|one quarter|
¾|three quarters|
²|squared superscript two|
³|cubed superscript three|
℃|degrees celsius|
⌘|command key|
⌥|option alt key|
⇧|shift key|
⌃|control key|
⎋|escape key|
⌫|delete backspace key|
⏎|return enter key|
★|black star|
☆|white star|
♪|music note|
♫|music notes|
µ|micro mu|
Ω|omega ohm|
Δ|delta change|
Σ|sigma sum|
α|alpha|
β|beta|
λ|lambda|"""

def main(path):
    out, seen = [], set()
    for line in open(path, encoding='utf-8'):
        m = re.match(r'^([0-9A-F ]+?)\s*; fully-qualified\s*# (\S+) E([0-9.]+) (.+)$', line.strip())
        if not m: continue
        cps, emoji, ver, name = m.groups()
        if float(ver) > MAX_VERSION or 'skin tone' in name or emoji in seen: continue
        seen.add(emoji)
        name = name.lower()
        words = ' '.join(w for key, w in ALIASES if (name == key[1:] if key.startswith('=') else key in name)).split()
        extra = ' '.join(dict.fromkeys(words))
        out.append(f'{emoji}|{name}|{extra}')
    out += SYMBOLS.split('\n')
    text = '\n'.join(out)
    assert '"""' not in text and '\\' not in text
    open('NotchApple/Core/EmojiData.swift', 'w', encoding='utf-8').write(
        '// Generated by scripts/gen_emoji.py from Unicode emoji-test.txt (Unicode License). Don\'t edit by hand.\n'
        'enum EmojiData {\n    static let raw = """\n' + text + '\n"""\n}\n')
    open('NotchWindows/src/js/services/emojidata.js', 'w', encoding='utf-8').write(
        '// Generated by scripts/gen_emoji.py from Unicode emoji-test.txt (Unicode License). Don\'t edit by hand.\n'
        'export const RAW = `' + text + '`;\n')
    print(len(out), 'entries')

main(sys.argv[1])
