// Every tab, in its default order. `feature` names the Pro/Ultimate feature a
// whole tab belongs to (as Module.feature does on the Mac); tabs without one are
// free. The blurbs are the Mac app's, adjusted where Windows does it differently.

export const MODULES = [
  { id: 'today', name: 'Today', icon: '☀️', load: () => import('./modules/today.js'),
    blurb: 'Weather with the hourly and week forecast, your next calendar events, and your PC at a glance.' },
  { id: 'ai', name: 'AI', icon: '✨', load: () => import('./modules/ai.js'),
    blurb: 'Chat with AI: free Gemini, Groq, OpenRouter or local Ollama, or paid Claude, ChatGPT and DeepSeek. Ask about your screen.' },
  { id: 'sports', name: 'Sports', icon: '⚽', load: () => import('./modules/sports.js'),
    blurb: 'Follow your team (Barcelona unless you pick another): next match, every competition, results and the live score on the pill.' },
  { id: 'f1', name: 'F1', icon: '🏁', load: () => import('./modules/f1.js'),
    blurb: 'Formula 1: the running order during sessions, the weekend schedule with a countdown, and standings.' },
  { id: 'nowplaying', name: 'Now Playing', icon: '🎵', load: () => import('./modules/nowplaying.js'),
    blurb: "What's playing on your PC (Spotify, browsers, Media Player…) with the cover, controls and lyrics. The cover shows on the pill." },
  { id: 'browser', name: 'Browser', icon: '🌐', load: () => import('./modules/browser.js'),
    blurb: 'Search the web or open a site from the notch, with your choice of search engine.' },
  { id: 'launcher', name: 'Launcher', icon: '🚀', feature: 'launcher', load: () => import('./modules/launcher.js'),
    blurb: 'Add the apps you use most and open them straight from the notch.' },
  { id: 'search', name: 'Search', icon: '🔍', load: () => import('./modules/search.js'),
    blurb: 'Find files, folders and apps instantly, then open them or show them in Explorer.' },
  { id: 'clipboard', name: 'Clipboard', icon: '📋', load: () => import('./modules/clipboard.js'),
    blurb: 'Keeps everything you copy (text, images and files), so you can find it and copy or paste it again.' },
  { id: 'notes', name: 'Notes', icon: '📝', load: () => import('./modules/notes.js'),
    blurb: 'Quick notes in the notch, saved automatically.' },
  { id: 'todo', name: 'To-do', icon: '✅', load: () => import('./modules/todo.js'),
    blurb: 'A to-do list with due dates and reminders.' },
  { id: 'focus', name: 'Focus', icon: '🎯', feature: 'focus', load: () => import('./modules/focus.js'),
    blurb: 'A Pomodoro focus timer with a countdown on the pill, session stats, and distraction blocking.' },
  { id: 'timer', name: 'Timer', icon: '⏱', load: () => import('./modules/timer.js'),
    blurb: 'A countdown timer and stopwatch with laps. The time left shows on the pill.' },
  { id: 'translator', name: 'Translator', icon: '🈯', load: () => import('./modules/translator.js'),
    blurb: 'Translate between Arabic, English, French, Spanish, Hindi, Mandarin and German, with pronunciation you can read and hear.' },
  { id: 'stats', name: 'PC Stats', icon: '📊', load: () => import('./modules/stats.js'),
    blurb: 'Live memory, CPU, network speed, battery and disk space, and the busiest apps.' },
  { id: 'worldclock', name: 'World Clock', icon: '🕐', load: () => import('./modules/worldclock.js'),
    blurb: 'The time in the cities you choose, with day or night and the difference, plus a meeting planner.' },
  { id: 'tools', name: 'Tools', icon: '🛠', load: () => import('./modules/tools.js'),
    blurb: 'Keep your PC awake, pick colours from the screen, a calculator, and a unit and currency converter.' },
  { id: 'shelf', name: 'Shelf', icon: '🗂', load: () => import('./modules/shelf.js'),
    blurb: 'Drop files and folders onto the notch to keep them handy.' },
  { id: 'windows', name: 'Windows', icon: '🪟', load: () => import('./modules/windows.js'),
    blurb: 'Snap the window you were using into halves, thirds and quarters, or tile everything at once.' },
  { id: 'games', name: 'Games', icon: '🎮', load: () => import('./modules/games.js'),
    blurb: 'Tiny games for a short break: 2048, Snake and a reaction test. Best scores stay on this PC.' },
  { id: 'markets', name: 'Markets', icon: '📈', feature: 'markets', load: () => import('./modules/markets.js'),
    blurb: "A watchlist of stocks and crypto with today's change; pin one to the pill." },
  { id: 'home', name: 'Home', icon: '🏠', feature: 'homeLayout', load: () => import('./modules/home.js'),
    blurb: 'Your own dashboard of widgets in small, medium and large sizes.' },
  { id: 'audio', name: 'Audio', icon: '🔊', feature: 'audio', load: () => import('./modules/audio.js'),
    blurb: 'Master volume, output device, microphone mute, and the volume of each app.' },
  { id: 'snippets', name: 'Snippets', icon: '✂️', feature: 'snippets', load: () => import('./modules/snippets.js'),
    blurb: 'Saved bits of text you paste into any app with one click.' },
  { id: 'voicenotes', name: 'Voice Notes', icon: '🎙', feature: 'voiceNotes', load: () => import('./modules/voicenotes.js'),
    blurb: 'Record a voice note from the notch; one click transcribes it and turns it into a summary with action items.' },
  { id: 'screentime', name: 'Screen Time', icon: '⌛', feature: 'screenTime', load: () => import('./modules/screentime.js'),
    blurb: 'See how long you spend in each app, set daily limits, and block distracting apps during Focus. Stays on your PC.' },
  { id: 'quickadd', name: 'Quick Add', icon: '⚡', feature: 'quickAdd', load: () => import('./modules/quickadd.js'),
    blurb: 'Type “Dentist tomorrow 3pm” or “remind me to pay rent on the 1st” and it becomes a to-do with a reminder, or a calendar event.' },
  { id: 'messenger', name: 'Messenger', icon: '💬', feature: 'messenger', load: () => import('./modules/messenger.js'),
    blurb: 'Chat in an end-to-end encrypted room joined by a code. Mac and Windows users can be in the same room.' },
  { id: 'mirror', name: 'Mirror', icon: '🪞', feature: 'mirror', load: () => import('./modules/mirror.js'),
    blurb: 'A mirror using your camera, to check how you look before a call. Nothing is recorded.' },
  { id: 'vpn', name: 'VPN', icon: '🛡', feature: 'vpn', load: () => import('./modules/vpn.js'),
    blurb: "Free VPN Gate servers through Windows' built-in VPN, or your own OpenVPN profile." },
  { id: 'devices', name: 'Devices', icon: '🎧', load: () => import('./modules/devices.js'),
    blurb: "What's using your microphone or camera (with a mic mute), your battery and connected devices." },
  { id: 'live', name: 'Parcels & Flights', icon: '📦', note: 'Not recommended: limited usefulness for most situations, low compatibility.', load: () => import('./modules/live.js'),
    blurb: 'Track parcels and flights from the notch, with live flight status.' },
  { id: 'actions', name: 'Actions', icon: '⚙️', load: () => import('./modules/actions.js'),
    blurb: 'One-click actions you set up: open apps, files and sites, run commands, and system shortcuts.' },
  { id: 'plugins', name: 'Plugins', icon: '🧩', load: () => import('./modules/plugins.js'),
    blurb: 'Your own widgets: any script in the Plugins folder shows its output in the notch.' },
  { id: 'share', name: 'Share', icon: '📤', load: () => import('./modules/share.js'),
    blurb: 'Send files to phones and other computers nearby with PairDrop, or with Windows Nearby sharing.' },
  { id: 'wellbeing', name: 'Wellbeing', icon: '🌿', load: () => import('./modules/wellbeing.js'),
    blurb: 'A breathing exercise, break reminders (eyes, water, stretch, posture) and a bedtime nudge.' },
  { id: 'devtools', name: 'Dev Tools', icon: '🛠', load: () => import('./modules/devtools.js'),
    blurb: 'Format JSON, encode and decode, read a JWT, hash, make a UUID, convert timestamps, test a regex, check colour contrast and make a QR code. Everything stays on this PC.' },
  { id: 'smarthome', name: 'Smart Home', icon: '💡', feature: 'smartHome', load: () => import('./modules/smarthome.js'),
    blurb: 'Control your Home Assistant lights, switches, scenes and more. Works with Hue, IKEA, Zigbee and Matter through Home Assistant.' },
  { id: 'claudeusage', name: 'Claude Usage', icon: '📟', feature: 'claudeUsage', load: () => import('./modules/claudeusage.js'),
    blurb: 'How many tokens Claude Code has used in your 5-hour window, today and this week, with budgets you set yourself. Read from your .claude folder on this PC.' },
  { id: 'settings', name: 'Settings', icon: '⚙', load: () => import('./modules/settings.js'),
    blurb: '' },
];

/// What a fresh install shows. Everything else is one click away in Settings → Tabs.
export const DEFAULT_ON = ['today', 'ai', 'sports', 'f1', 'nowplaying', 'search', 'clipboard', 'notes', 'todo', 'timer', 'shelf', 'windows', 'tools',
  'stats', 'worldclock', 'games', 'markets', 'home', 'audio', 'settings'];

export const byId = (id) => MODULES.find((m) => m.id === id);
